run_name: stage1
fast_epoch: False

conv_mode: emo_llama

per_device_train_batch_size: 1
dataloader_num_workers: 6

use_cap: False
use_img: True

use_im_start_end: True
use_im_patches: True

json_file_train:  # Training data in Google Drive
json_file_val:  # Testing data in Google Drive

llm_path:  #LLama2 7b location
vit_path:  # CLIP VIT Large location

image_paths:  # Path to the selected frames for training
reason_path:  # Path to the reasons for training


freeze_llm: True
freeze_backbone: True

num_convos: 1
num_train_epochs: 3


